ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "S_elongatus"
  site-url: "https://LifeWorks.github.io/S_elongatus"
  description: "The computational model of Synechococcus elongatus"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/LifeWorks/S_elongatus"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/LifeWorks/S_elongatus"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
