# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/S_elongatus',
                'doc_host': 'https://LifeWorks.github.io',
                'git_url': 'https://github.com/LifeWorks/S_elongatus',
                'lib_path': 'S_elongatus'},
  'syms': {'S_elongatus.core': {'S_elongatus.core.foo': ('core.html#foo', 'S_elongatus/core.py')}}}